making banker joe flashloans completely compliant with EIP-3156
traderjoe-xyz/joe-lending pull request #25
Opened 2022-06-01 12:17 UTC by Mathieu-Be

This PR makes Banker Joe flashloans 100% compliant with [EIP-3156](https://eips.ethereum.org/EIPS/eip-3156).

I also modified deploy scripts in order to use a single `JCollateralCapErc20Delegate` implementation. I deployed this for fuji, new addresses are included.

2022-06-01 14:52 UTC, LouisMeMyself approved these changes
Good stuff!

2022-06-02 10:13 UTC, cryptofish7 requested changes

2022-06-02 10:13 UTC, cryptofish7 commented on deploy/JERC20Delegate.js
> +  await deploy("JERC20Delegate", {
Change this to `JCollateralCapErc20Delegate` because there's a `JErc20Delegate.sol` already.

2022-06-02 16:16 UTC, cryptofish7 approved these changes

2022-06-02 16:17 UTC, merged